### ISSUE TITLE
Use better properties for animation

### ISSUE THREAD

**Issue by joostf** [boudewijnbout/saml-zelftestapp-campaign-website-flow#12]
https://github.com/boudewijnbout/saml-zelftestapp-campaign-website-flow/blob/48daee5cc86f3d021274dc813fd2ed06a49d5311/styles/header.css#L24-L38

transform
opacity

60fps animations
https://csstriggers.com/

**Comment by boudewijnbout** [comment]
Used the transform: translateX property for the animation.
